DOC_ROUTES = [
    {
        "id": "fast_start",
        "name": "Fast Start",
        "best_for": "Participants who need a clean first run as quickly as possible.",
        "outcome": "A working local environment and a first remember / recall smoke test.",
        "steps": [
            {
                "title": "Installation",
                "url": "https://docs.cognee.ai/getting-started/installation",
                "why": "Set up Python, a virtual environment, Cognee, and provider configuration.",
                "deliverable": "Confirm Python 3.10-3.14 and install Cognee in a clean environment.",
                "hackathon_use": "This prevents setup uncertainty from eating into build time.",
                "note_prompt": "Write your install path, Python version, package manager, and API key mode.",
            },
            {
                "title": "Quickstart",
                "url": "https://docs.cognee.ai/getting-started/quickstart",
                "why": "Run the smallest useful Cognee example and see memory retrieval work.",
                "deliverable": "Run a remember / recall script and capture the output.",
                "hackathon_use": "This gives your team a tiny proof that Cognee memory works before customization.",
                "note_prompt": "Paste the smoke-test result and one sentence about what it proves.",
            },
        ],
    },
    {
        "id": "hackathon_mvp",
        "name": "Hackathon MVP",
        "best_for": "Teams building a small demo around custom docs or sponsor materials.",
        "outcome": "A scoped demo plan with docs, ingestion assumptions, and test questions.",
        "steps": [
            {
                "title": "Installation",
                "url": "https://docs.cognee.ai/getting-started/installation",
                "why": "Make the local setup reproducible before adding hackathon-specific files.",
                "deliverable": "Document the install path and API key mode.",
                "hackathon_use": "A reproducible setup makes it easier for teammates and judges to run the demo.",
                "note_prompt": "Write the setup steps your team will include in the README.",
            },
            {
                "title": "Quickstart",
                "url": "https://docs.cognee.ai/getting-started/quickstart",
                "why": "Understand the minimum Cognee loop before customizing it.",
                "deliverable": "Write one project-specific remember / recall use case.",
                "hackathon_use": "This turns Cognee from an abstract dependency into your first user-facing workflow.",
                "note_prompt": "Describe the first memory item and the first question your app should answer.",
            },
            {
                "title": "Loaders",
                "url": "https://docs.cognee.ai/core-concepts/further-concepts/loaders",
                "why": "Check which document formats fit the materials your team has.",
                "deliverable": "List the files you will add and any optional extras needed.",
                "hackathon_use": "This helps choose a data scope small enough to demo reliably.",
                "note_prompt": "List your documents, formats, and any parsing concerns.",
            },
            {
                "title": "Setup Configuration",
                "url": "https://docs.cognee.ai/setup-configuration/overview",
                "why": "Choose provider and embedding settings without hard-coding secrets.",
                "deliverable": "Create a local .env plan for BYOK mode.",
                "hackathon_use": "This keeps the demo local-first while still allowing real AI features later.",
                "note_prompt": "Write the environment variables your project will need.",
            },
        ],
    },
    {
        "id": "agent_memory_demo",
        "name": "Agent Memory Demo",
        "best_for": "Teams showing how an assistant can remember project or user context.",
        "outcome": "A demo story that explains memory, retrieval, and agent usefulness.",
        "steps": [
            {
                "title": "Quickstart",
                "url": "https://docs.cognee.ai/getting-started/quickstart",
                "why": "Start from the core memory operations before adding agent behavior.",
                "deliverable": "Explain remember and recall in your own project language.",
                "hackathon_use": "This gives judges a simple mental model for why Cognee matters.",
                "note_prompt": "Write how your assistant will remember and retrieve context.",
            },
            {
                "title": "Core Concepts",
                "url": "https://docs.cognee.ai/core-concepts/overview",
                "why": "Understand the architecture well enough to explain it to judges.",
                "deliverable": "Write a plain-English description of how Cognee supports your app.",
                "hackathon_use": "A clear architecture explanation makes the demo feel intentional.",
                "note_prompt": "Summarize the Cognee concept your team needs to explain.",
            },
            {
                "title": "Agent Memory Quickstart",
                "url": "https://docs.cognee.ai/guides/agent-memory-quickstart",
                "why": "Connect Cognee memory to an agent-style workflow.",
                "deliverable": "Draft the agent memory scenario you want to demonstrate.",
                "hackathon_use": "This anchors the demo in an assistant workflow instead of a generic Q&A box.",
                "note_prompt": "Describe the agent memory scenario and what the user should experience.",
            },
        ],
    },
    {
        "id": "custom_docs_qa",
        "name": "Custom Docs Q&A",
        "best_for": "Teams building a question-answering helper over docs, notes, or PDFs.",
        "outcome": "A grounded Q&A plan with test questions and source materials.",
        "steps": [
            {
                "title": "Loaders",
                "url": "https://docs.cognee.ai/core-concepts/further-concepts/loaders",
                "why": "Match your source files to Cognee-supported loaders.",
                "deliverable": "Choose a small set of documents for the first demo.",
                "hackathon_use": "A small, relevant document set improves answer quality and demo speed.",
                "note_prompt": "List the exact docs you will use for the first Q&A demo.",
            },
            {
                "title": "Cognify",
                "url": "https://docs.cognee.ai/core-concepts/main-operations/cognify",
                "why": "Understand how raw data becomes structured memory.",
                "deliverable": "Describe what needs to happen after documents are added.",
                "hackathon_use": "This helps explain the transformation from files to usable AI memory.",
                "note_prompt": "Write what should happen after your docs are ingested.",
            },
            {
                "title": "Remember / Recall",
                "url": "https://docs.cognee.ai/getting-started/quickstart",
                "why": "Map your Q&A behavior to the basic memory storage and retrieval loop.",
                "deliverable": "Draft three grounded test questions for your materials.",
                "hackathon_use": "Judges can quickly see whether answers come from your selected materials.",
                "note_prompt": "Write three questions and what a grounded answer should mention.",
            },
            {
                "title": "Setup Configuration",
                "url": "https://docs.cognee.ai/setup-configuration/overview",
                "why": "Prepare model and embedding configuration for BYOK mode.",
                "deliverable": "Write the configuration variables your demo will need.",
                "hackathon_use": "This keeps keys local and makes provider choices explicit.",
                "note_prompt": "Write the BYOK variables and any provider decisions.",
            },
        ],
    },
]
